### PR TITLE
create+write HPCAI23.md

### PR DESCRIPTION
**Pull request by trkk28097402**

### CODE REVIEW

**Comment by William-Mou** [comment]
Thank you so much!
@jchou-git Here is the article about the contest HPCAI 2023 written by @trkk28097402
He expects to finish writing by the weekend, at which time I will merge the PR.

**Comment by trkk28097402** [comment]
@William-Mou I finished the article, you may check it. thx!

**Comment by trkk28097402** [comment]
ah sorry I found that I forget to add the last part, I will add a commit.

**Review by William-Mou — APPROVED** [review]
@trkk28097402 LGTM!

**Pull request merged**
